menu:
  article: /
  tags: /tags
  about: /about
  rss: /atom.xml
  travelling: https://www.travellings.cn/plain.html

favicon: /favicon.ico
copyright_license: 'License: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 License</a>'
github: 84634E1A607A
since: 2024
search_label: Search something?
